version: "3"
services:
  web-tomcat:
    ports:
     - 8080:8080
    build:
      context: ./
      args:
          - GIT_USR=<git_login>
          - GIT_PWD=<git_password>
    links:
    - db
  
  db:
    image: mysql:5.7
    ports:
     - 3306:3306
    environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_USER=login
       - MYSQL_PASSWORD=password
       - MYSQL_DATABASE=union_reporting
    volumes:
    - ./dump(1).sql:/docker-entrypoint-initdb.d/init.sql:ro
